language: node_js
sudo: false
node_js:
- node
- '6.0'
notifications:
  slack:
    - secure: iUeal9RUvRQCAa77YKviX7UnAyTJfmKwsiMH7fN7YZGx3aVxTAcyZ9/zY3uZnVKfaXWhUKDgwRQDSQxEDAIhsq2tPm0EY+dUAVAUUrKIJ4BSRlxm8C8hfgyBRXz2lYGDP84Rm4rtE1SskKDPR1XLJkYUSsPF3yixnR/JuTwoxeEto00TKaAfECHLn01BU+Ki60h8N9milknMH6wW1cpOXPbqdskJ1MHRuD+UnZXCvmjm9Su0BApLYjPEX3pOmwaMegY4IuDaE9zay+kw1rC5U+7A0RMTDoaFFDkbPQeSerEhDQU41xy3BPlZPiWscLIY4BtWDpdiG8IhPV8CsVBjZS1jG5BM3klvl0IZBZnTbI3zhmP2g8fmHYl4rx6Vw1tk8kPB8/wPsBTmt20rHJSHXpiPjU8M3XpSiQrch+MVnugGfC79BBhPTsFtNJoUaG0DroF6sCmFnvin+1CXRfcYcSQ3g1XAnuPNhz9AXTFZ9LDfj7ddA9Z+FFk/dEy+L0xU1uZC24aatp4YDiLD/OraIyVo3Y6GIuNBPIMFTlGTI6d1vVuYV+fsdbQtqh/EzfY0IxGAgjGOzIJbHCcJWKtGOqs4/xU9FPsBbWV0CNlmSR0NzqHI5I1cfSn+83YOAGKtdvOJ5WbiOgk+F8/DXacJ7jdMaEw6V4iVJ/tDSAOAsf0=
    - on_failure: always
    - on_success: never
