language: node_js
sudo: false
node_js:
- node
- '6.0'
notifications:
  slack:
    rooms:
      secure: e8z5TiAx+/RiE3ON8YaymAYtUySm+vNCVfPpk7k1FNN8Jsomv7F02semVLzk3prrLjxujqc7eF//UJlkmrfOd8QsqyYKST4M2wa72PAwYzULpTmejBDsbad6+0WyRFjHCf1SvIOx7T6pB2cw2hjrJyeLpPBQSsMnHYjGox9+Q0e1UvZ+rDButnBa4wZ+c2+cYXjIcNQuPP6y1THBx29RcNttptT5aEIcbXXNdyWFYDHP9guy/byZ/GTaEq0lwDT7lDSXU+rXgTRsQtxMiNh8ZBc9FwkJNOXs4bTr1lc9tBx8GyNAT/Tck6y25dsMk64SnD8AOaPYt04OEktD2fh/9RkDPB2GO8Zrs0frgLwIrm3bOdlGbFLhXpqB5+pFYKQYWz83avS3U/ulcNjnM0ttOxWeM4+lzQWJzal2D7TrmGaJWGZBApJvy9DJbewE8WbfaYK/Ftapwnp3PbS1QdNbXPmEvyYWcdiW9bhBFa0SUMeUFYGaY4HWGEOiJrpFJyvehe8FPReRI1B7yE2GjSLgzpggH4hZoAkZPZ7BNewoEBQCaHjZI5kVi3MmkwRv5rAHAW4R0JH0SRajDq+PY4bmqzA4H+skRjoLODrrh450tJwqjz0xejtlK4urN1VMEwTsD2g1RLbFpsBVtx2Be3b++ioUfiRazDjS7wcVc2qFJXE=
    on_success: never
    on_failure: always
