language: node_js
sudo: false
node_js:
- node
- '6.0'
notifications:
  slack:
    rooms:
      secure: HlZ5NBM8mUJwjw1GTsl8myGs6APzGnw2wdIK5pVKt4unL9nl326aFMcdVSbKVkNojKRGOOLSKYlfRV+Q4PJzndAGKqua1sU5XBIBEiS4GEDpeVBFyC2kKAsjJYW352Jbq0mK05vYIA5nRAOBVTor9lwf/9gDO87R1zqRqW8fIveWya5DImjoCeADTMWjSum+pEpXYwsNnkWovR9/JayY6gkwdiL60ygCJCGmcdXS+TGfhR56lv9hD79nI0To5F2BGv1hvUuom560wi2eqNXMsa25U3EJyYA5ywcFI3/kmBcXb7L39/gk1bW2jITSav51PJEjkjCY7iDCZmPeVvpjTLitnsPum8uI6GDpEGV/vw2955RE/0msDZ65VtOWXz2FNLIrFWjM401r7FgykF8TjJbq1OgojuevzUyTJI11apKyD/5f0GSVOjl4v1ZY3qemwfXvPMN+6bFpmr/DwX1zkZ6W6/c7Pqann6Z/58E4CT/wGDIXOLPBLehg/1/5PhIJWd4ypGlH2aMn+PMbNwFGeMmtZjcpSuG0dkunj/RDjHg8Cexz0EK64n4bRr19hQ+K9P6JGjiec78WkXWpORmhfFAUv5QXd/I39BxByX+62LdvbCV3nDzgGHvHMRzWYVcAKVXOb9qyjmE94ggMQXVVN5AyyZ60XZ1iDWGKqWwKbxw=
    on_success: change
    on_failure: always
