#!/usr/bin/env node
const mkdirp    = require( 'mkdirp' )
const path      = require( 'path' )

createBinDirectory( 'bundles' )
    .then( () => createBinDirectory( 'database' ) )
    .then( success )
    .catch( raiseError )

function raiseError( error ) {
    console.log( `Error when creating build binaries directories: ${error}` )
    process.exit()
}

function success() {
    console.log( '\nMade with success. Compiling binaries...\n' )
    process.exit()
}

function createBinDirectory( binary ) {
    return new Promise( ( resolve, reject ) => {
        const binPath = path.resolve( `./build/bin/${binary}` )

        mkdirp( binPath, error => {
            if ( error ) {
                reject( error )
            } else {
                console.log( `${binPath} created` )
                resolve()
            }
        })
    })
}
