/*
* This file is part of the easy framework.
*
* (c) Julien Sergent <sergent.julien@icloud.com>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

require( 'use-strict' )

global.easy = global.easy || {}

const path = require( 'path' )
const { Application, Console } = require( 'easy/core' )
/*
 * Either the application root path is generated by the cli or this file is required by server.js file, and process.argv[ 1 ] contains it's path
 */
const appRootPath = easy.appRootPath || path.resolve( `${process.argv[ 1 ]}/../../../` )
const application = new Application()

try {
	application.configure( appRootPath )
} catch ( error ) {
	Console.error({ title: 'The configuration of the application has failed', message: error.stack || error, consequence: 'Application stopped' })
	process.exit()
}

module.exports = { application }
